-- Source tables are kept as-is:
-- public.raw_file
-- public.item_plc
-- public.center_stock

create table if not exists public.sku_weekly_base (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  year_week text not null,
  week_no integer not null,
  plant text not null,
  style_code text not null,
  sku text not null,
  item_code text null,
  sale_qty numeric not null default 0,
  ipgo_qty numeric not null default 0,
  stock_change_qty numeric not null default 0,
  base_stock_qty numeric not null default 0,
  ending_stock_qty numeric not null default 0,
  stage text null,
  shape_type text null,
  peak_week integer null,
  peak_month integer null,
  last_year_ratio_pct numeric null,
  sale_end_date date null,
  is_peak_week boolean not null default false,
  source_type text not null default 'actual',
  unique (style_code, sku, plant, year_week)
);

create table if not exists public.sku_weekly_forecast_plan (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  plan_run_id uuid not null default gen_random_uuid(),
  year_week text not null,
  week_no integer not null,
  plant text not null,
  style_code text not null,
  sku text not null,
  stage text null,
  shape_type text null,
  last_year_ratio_pct numeric null,
  base_stock_qty numeric not null default 0,
  sale_qty numeric not null default 0,
  ipgo_qty numeric not null default 0,
  cumulative_sale_qty numeric not null default 0,
  cumulative_ipgo_qty numeric not null default 0,
  total_owned_stock_qty numeric not null default 0,
  depletion_rate_pct numeric not null default 0,
  is_peak_week boolean not null default false,
  is_forecast boolean not null default false,
  loss_qty numeric not null default 0,
  sale_end_date date null,
  unique (style_code, sku, plant, week_no, plan_run_id)
);

create table if not exists public.store_season_need (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  plan_run_id uuid not null,
  style_code text not null,
  sku text not null,
  center text not null,
  current_stock_qty numeric not null default 0,
  cumulative_ipgo_qty numeric not null default 0,
  cumulative_sale_qty numeric not null default 0,
  remaining_need_qty numeric not null default 0,
  season_end_date date null
);

create table if not exists public.purchase_recommendation (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  plan_run_id uuid not null,
  style_code text not null,
  sku text not null,
  plant text not null,
  recommended_order_week text not null,
  recommended_order_qty numeric not null default 0,
  expected_shortage_week text null,
  safety_stock_qty numeric not null default 0,
  lead_time_weeks integer not null default 2,
  reason text null
);

create or replace view public.sku_weekly_forecast_preview as
select
  b.year_week,
  b.week_no,
  b.plant,
  b.style_code,
  b.sku,
  b.stage,
  b.shape_type,
  b.last_year_ratio_pct,
  b.base_stock_qty,
  b.sale_qty,
  b.ipgo_qty,
  b.is_peak_week,
  case when b.source_type = 'forecast' then true else false end as is_forecast
from public.sku_weekly_base b;
